// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// read_cmdstan_csv
Rcpp::List read_cmdstan_csv(Rcpp::StringVector file);
RcppExport SEXP _stannis_read_cmdstan_csv(SEXP fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type file(fileSEXP);
    rcpp_result_gen = Rcpp::wrap(read_cmdstan_csv(file));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_stannis_read_cmdstan_csv", (DL_FUNC) &_stannis_read_cmdstan_csv, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_stannis(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
