# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rewrite <- function(source, root, tag, comment) {
    .Call('_stannis_rewrite', PACKAGE = 'stannis', source, root, tag, comment)
}

