# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_cmdstan_csv <- function(file) {
    .Call('_stannis_read_cmdstan_csv', PACKAGE = 'stannis', file)
}

